# Starter pipeline
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  -group: nuget

steps:
- script: dotnet restore ./srcs/Xamarin.OneDrive.Connector
  displayName: 'msbuild ./srcs/Xamarin.OneDrive.Connector /t:restore'
- script: msbuild ./srcs/Xamarin.OneDrive.Connector /t:build /p:Configuration=$(buildConfiguration)
  displayName: 'dotnet build '
- script: msbuild ./srcs/Xamarin.OneDrive.Connector /t:pack /p:Configuration=$(buildConfiguration)
  displayName: 'dotnet pack'
- script: dotnet nuget push ./srcs/Xamarin.OneDrive.Connector/bin/Release/*.nupkg -k $(nugetApiKey) -s $(nugetApiUrl)
  displayName: 'dotnet nuget push'
