# Starter pipeline
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  -group: nuget

steps:
- script: msbuild ./srcs/Xamarin.OneDrive.Connector /t:restore
  displayName: 'restore packages'

- task: MSBuild@1 
  displayName: build assemblies
  inputs:
    solution: ./srcs/Xamarin.OneDrive.Connector\Xamarin.OneDrive.Connector.csproj
    configuration: $(buildConfiguration)
    # msbuildArguments: 

- script: msbuild ./srcs/Xamarin.OneDrive.Connector /t:pack /p:Configuration=$(buildConfiguration)
  displayName: 'package binaries'

- script: dotnet nuget push **/Xamarin.OneDrive.Connector*.nupkg -k $(nugetApiKey) -s $(nugetApiUrl)
  displayName: 'publish nuget'
